# Generated by Django 5.2.3 on 2025-06-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="redemption",
            name="partner_confirmation_id",
            field=models.CharField(
                blank=True,
                help_text="Confirmation ID from partner system, if applicable",
                max_length=255,
                null=True,
            ),
        ),
    ]
